/**
 * Builds content/reference/top20k-en.txt: the top 20,000 English words from wordfreq, used only by
 * `pnpm content:check` rule 9 (pseudowords; docs/DECISIONS.md #7). Never imported from src/.
 *
 * Reproducible without Python: downloads the pinned wordfreq wheel from PyPI, verifies its sha256,
 * and decodes the bundled `large_en.msgpack.gz` ("cB" format: a header, then buckets of words by
 * descending frequency). Iterating buckets in order is exactly wordfreq's
 * `top_n_list("en", 20000)` (wordlist "best" = "large" for English, ascii_only=False).
 *
 * Usage: pnpm content:build-reference   (network needed; the output is committed)
 */
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { gunzipSync } from "node:zlib";
import { decode } from "@msgpack/msgpack";
import { unzipSync } from "fflate";

const WORDFREQ_VERSION = "3.1.1";
const WHEEL_URL =
  "https://files.pythonhosted.org/packages/24/61/62835c475d69872d30689f284497853fe33fe1d6dd18f57346d13305861d/wordfreq-3.1.1-py3-none-any.whl";
const WHEEL_SHA256 = "4b1c6ecffc6198be3396d5cf871c4423ca71c907c231348d352dd54d62b97473";
const DATA_PATH = "wordfreq/data/large_en.msgpack.gz";
const TOP_N = 20_000;
// Kept after taking the top N: plain lowercase words (apostrophes/hyphens allowed). Numbers,
// symbols and non-ASCII tokens can never collide with an ASCII pseudoword anyway.
const KEEP = /^[a-z][a-z'-]*$/;

const OUT = resolve(import.meta.dirname, "../../content/reference/top20k-en.txt");

async function main() {
  const res = await fetch(WHEEL_URL);
  if (!res.ok) throw new Error(`download failed: ${res.status}`);
  const wheel = new Uint8Array(await res.arrayBuffer());
  const sha = createHash("sha256").update(wheel).digest("hex");
  if (sha !== WHEEL_SHA256) throw new Error(`sha256 mismatch: ${sha}`);

  const file = unzipSync(wheel, { filter: (f) => f.name === DATA_PATH })[DATA_PATH];
  if (!file) throw new Error(`${DATA_PATH} not found in wheel`);
  const data = decode(gunzipSync(file)) as [{ format: string; version: number }, ...string[][]];
  const [header, ...buckets] = data;
  if (header.format !== "cB" || header.version !== 1) throw new Error("unexpected cBpack header");

  const top: string[] = [];
  outer: for (const bucket of buckets) {
    for (const word of bucket) {
      top.push(word);
      if (top.length >= TOP_N) break outer;
    }
  }
  const words = [...new Set(top.map((w) => w.toLowerCase()).filter((w) => KEEP.test(w)))];

  const headerLines = [
    `# Top ${TOP_N} English words from wordfreq ${WORDFREQ_VERSION} (large_en), filtered to ${KEEP}.`,
    `# Wheel sha256 ${WHEEL_SHA256}. Data license CC-BY-SA 4.0 — see content/SOURCES.md.`,
    `# Generated by scripts/content/build-reference.ts. Internal validation only; never shipped.`,
  ];
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, [...headerLines, ...words].join("\n") + "\n");
  console.log(`wrote ${words.length} words (of top ${top.length}) to ${OUT}`);
}

await main();
