/**
 * `pnpm content:noa` — English headwords from review/input/noa.docx (untracked: it holds Noa's
 * Hebrew translations) → content/reference/candidates/noa.txt, plus review/noa-typos.csv listing
 * every annotated item and its resolution (noa.ts). Never writes any Hebrew.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { unzipSync } from "fflate";
import { extractNoa, docxParagraphs } from "./noa";
import { parseCefrj, parseFamilies, readSource, REFERENCE_DIR, SOURCES } from "./sources";

const ROOT = resolve(import.meta.dirname, "../..");
const DOCX = join(ROOT, "review/input/noa.docx");
const OUT = join(REFERENCE_DIR, "candidates/noa.txt");
const TYPOS = join(ROOT, "review/noa-typos.csv");

const xml = unzipSync(readFileSync(DOCX), { filter: (f) => f.name === "word/document.xml" })[
  "word/document.xml"
];
if (!xml) throw new Error("word/document.xml not found");

const known = new Set([
  ...readFileSync(join(REFERENCE_DIR, "top20k-en.txt"), "utf8").split("\n"),
  ...parseCefrj(readSource(SOURCES.cefrj)).map((e) => e.headword),
  ...parseFamilies(readSource(SOURCES.nawlFamilies)).flatMap((f) => [f.lemma, ...f.forms]),
]);
const noa = extractNoa(docxParagraphs(new TextDecoder().decode(xml)), known);
for (const w of noa.headwords) if (/[^\x20-\x7e]/.test(w)) throw new Error(`non-ASCII: ${w}`);

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  [
    "# English headwords from Noa's word list (permission confirmed; content/SOURCES.md).",
    "# Headwords only, never her translations. Generated by pnpm content:noa.",
    ...noa.headwords,
  ].join("\n") + "\n",
);
const csv = (s: string) => (/[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s);
const annotated = noa.resolutions.filter((r) => r.annotation);
writeFileSync(
  TYPOS,
  "﻿" +
    [
      "original,annotation,annotation_word,resolution,headword,reason,decision",
      ...annotated.map((r) =>
        [
          r.original,
          r.annotation!.kind,
          r.annotation!.word,
          r.status,
          r.headword ?? "",
          r.reason,
          "",
        ]
          .map(csv)
          .join(","),
      ),
    ].join("\r\n") +
    "\r\n",
);
console.log(JSON.stringify(noa.counts));
for (const r of annotated) console.log(`${r.original} → ${r.headword ?? "(pending)"}: ${r.reason}`);
